[env]
JAVA_HOME = "/Applications/Android Studio.app/Contents/jbr/Contents/Home"
ANDROID_HOME = "/Users/makoto-mori/Library/Android/sdk"
NDK_HOME = "/Users/makoto-mori/Library/Android/sdk/ndk/27.1.12297006/"

[tools]
rust = "latest"
pnpm = "latest"
node = "latest"
