name: Build and Lint React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.11.0

      - name: Install dependencies
        run: pnpm i

      - name: Run lint
        run: pnpm run lint

      - name: Run build
        run: pnpm run build
